pipeline {
    environment {
        AWS_ACCESS_KEY_ID = credentials("AWS_ACCESS_KEY_ID")
        AWS_SECRET_ACCESS_KEY = credentials("AWS_SECRET_ACCESS_KEY")
        AWS_DEFAULT_REGION = "eu-west-1"
        DOCKERHUB_ID = "matiasroje"
        DOCKERHUB_PASSW = credentials("DOCKERHUB_PASSW")
    }
    agent any

    stages {
        stage("Git Checkout") {
            steps {
                git(
                    url: "https://github.com/MatiasRoje/spring-petclinic-cloud.git",
                    branch: "staging",
                    credentialsId: "GITHUB_ID"
                )
            }
        }
        stage("Setup Env Variable") {
            steps {
                script {
                    env.REPOSITORY_PREFIX = "${DOCKERHUB_ID}"
                    echo "Repository Prefix set to: ${env.REPOSITORY_PREFIX}"
                }
            }
        }
        stage("Build and Push Images") {
            steps {
                withMaven(maven: "Maven3.9.9") {
                    sh '''
                        docker --version
                        echo $DOCKERHUB_PASSW | docker login -u $DOCKERHUB_ID --password-stdin

                        # Build images
                        mvn -X spring-boot:build-image -Pk8s -DREPOSITORY_PREFIX=$DOCKERHUB_ID

                        # Push images
                        docker push $DOCKERHUB_ID/spring-petclinic-cloud-api-gateway:latest
                        docker push $DOCKERHUB_ID/spring-petclinic-cloud-visits-service:latest
                        docker push $DOCKERHUB_ID/spring-petclinic-cloud-vets-service:latest
                        docker push $DOCKERHUB_ID/spring-petclinic-cloud-customers-service:latest

                        echo 'Images built and pushed successfully.'

                        # Clean up local Docker images
                        docker image prune -af
                    '''
                }
            }
        }
    }
}